name: Check markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ["self-hosted", "general-ubuntu-amd"]
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@master
